/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia4;

/**
 *
 * @author ESTUDIANTE 25
 */
public class EPS extends javax.swing.JFrame {

    /**
     * Creates new form EPS
     */
    public EPS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escrito = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        llenDat = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        verPA = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escrito.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout escritoLayout = new javax.swing.GroupLayout(escrito);
        escrito.setLayout(escritoLayout);
        escritoLayout.setHorizontalGroup(
            escritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritoLayout.setVerticalGroup(
            escritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("PIDA TURNO");

        llenDat.setSelected(true);
        llenDat.setText("Llenado de datos.");
        llenDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llenDatActionPerformed(evt);
            }
        });
        jMenu1.add(llenDat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("PACIENTES EN ESPERA");

        verPA.setSelected(true);
        verPA.setText("VER PACIENTES EN ESPERA");
        verPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPAActionPerformed(evt);
            }
        });
        jMenu2.add(verPA);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escrito)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escrito)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPAActionPerformed
        MostradodePacientes verpacientes = new MostradodePacientes();
        escrito.add(verpacientes);
        verpacientes.show();
    }//GEN-LAST:event_verPAActionPerformed

    private void llenDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llenDatActionPerformed
        llenadodeDatos digitedats = new llenadodeDatos();
        escrito.add(digitedats);
        digitedats.show();
    }//GEN-LAST:event_llenDatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escrito;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem llenDat;
    private javax.swing.JCheckBoxMenuItem verPA;
    // End of variables declaration//GEN-END:variables
}
